dataset_name = "ogbl-collab"

[sampling]
n_samples = 1
sampling_fn = "basic"

[features]
common_neighbors_count = false
common_neighbor_centrality = false
jaccard_coefficient = true
adamic_adar_index = true
preferential_attachment = true
resource_allocation_index = true

[model]
scaling = "normalise"
n_estimators = 201
